### ISSUE TITLE
Install command will fail with updated install.sh script

### ISSUE THREAD

**Issue by jondegenhardt** [lindt/docker-dmd#3]
The command:

`bash /tmp/install.sh -p /dlang install -s "${COMPILER}-${COMPILER_VERSION}"`

fails with recent changes to the install.sh script on the site. See dlang/installer#258. The change is to validate arguments, and -s is not a recognized argument. This will affect the docker-ldc Dockerfile as well.

**Comment by lindt** [comment]
thanks jon.
ldc merged just now.
also did the fix for dmd.
